### PR TITLE
Install tips in README.md

### PR DESCRIPTION
**Pull request by tescher**
Added a couple troubleshooting tips that I ran into while installing cd with a bare VM (no Docker or Vagrant), but that could potentially also apply to at least the Docker-flavored install.

### CODE REVIEW

**Comment by tescher** [comment]
It appears that the Docker section of the README is a bit twisted. I know next to nothing about Docker configs, but looking at the config files in the repo it appears that Docker is supposed to be handling some of the tasks that the README tells the installer to do. Someone who knows Docker should probably review this section. I can write up an issue if this is truly a problem.

**Comment by thermokarst** [comment]
Yes, the docker section is outdated, and should most likely be removed. It was included for internal use, and is not necessary since Scott put together a Vagrant config. Specifically, the Docker section was for a demo instance of the app, used for internal review of the application.

**Comment by tescher** [comment]
OK. Given that I suppose it could be argued that Vagrant might obviate the need for my install tips (since it basically installs an image?), but I think I would argue for keeping them in there because a bare (non-Vagrant) install is still a useful thing to be able to do, especially if new extensions/infrastructure needs to be added.

**Comment by thermokarst** [comment]
I agree that the README should include the steps necessary to recreate the application environment manually, your additions are certainly useful.

**Comment by thermokarst** [comment]
This looks good to me. Thanks!

**Pull request merged**
